# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gauss_easter_algorithm_Cpp <- function(year) {
    .Call('_DutchDayDummies_gauss_easter_algorithm_Cpp', PACKAGE = 'DutchDayDummies', year)
}

ummalqura_algorithm_Cpp <- function(day, month, year) {
    .Call('_DutchDayDummies_ummalqura_algorithm_Cpp', PACKAGE = 'DutchDayDummies', day, month, year)
}

